#####----------------------------------------------------------------------#####
##### Input filter params
#####----------------------------------------------------------------------#####
config.params <- list(
  v0.1 = list(nFeatureRNAfloor = NULL,
              nFeatureRNAceiling = NULL,
              nCountRNAfloor = NULL, 
              nCountRNAceiling = NULL,
              pct_mitofloor = NULL, 
              pct_mitoceiling = 10,
              pct_ribofloor = NULL, 
              pct_riboceiling = NULL,
              ambientRNA_thres = 0.5),
  v0.2 = list(nFeatureRNAfloor = NULL,
              nFeatureRNAceiling = NULL,
              nCountRNAfloor = NULL, 
              nCountRNAceiling = NULL,
              pct_mitofloor = NULL, 
              pct_mitoceiling = 25,
              pct_ribofloor = NULL, 
              pct_riboceiling = NULL,
              ambientRNA_thres = 0.5),
  v0.3 = list(nFeatureRNAfloor = NULL,
              nFeatureRNAceiling = NULL,
              nCountRNAfloor = NULL, 
              nCountRNAceiling = NULL,
              pct_mitofloor = NULL, 
              pct_mitoceiling = 10,
              pct_ribofloor = NULL, 
              pct_riboceiling = NULL,
              ambientRNA_thres = 0.75),
  v0.4 = list(nFeatureRNAfloor = NULL,
              nFeatureRNAceiling = NULL,
              nCountRNAfloor = NULL, 
              nCountRNAceiling = NULL,
              pct_mitofloor = NULL, 
              pct_mitoceiling = 25,
              pct_ribofloor = NULL, 
              pct_riboceiling = NULL,
              ambientRNA_thres = 0.75),
  v0.5 = list(nFeatureRNAfloor = NULL,
              nFeatureRNAceiling = NULL,
              nCountRNAfloor = NULL, 
              nCountRNAceiling = NULL,
              pct_mitofloor = NULL, 
              pct_mitoceiling = 30,
              pct_ribofloor = NULL, 
              pct_riboceiling = NULL,
              ambientRNA_thres = 0.5),
  v0.6 = list(nFeatureRNAfloor = NULL,
              nFeatureRNAceiling = NULL,
              nCountRNAfloor = NULL, 
              nCountRNAceiling = NULL,
              pct_mitofloor = NULL, 
              pct_mitoceiling = 40,
              pct_ribofloor = NULL, 
              pct_riboceiling = NULL,
              ambientRNA_thres = 0.5),
  v0.7 = list(nFeatureRNAfloor = NULL,
              nFeatureRNAceiling = NULL,
              nCountRNAfloor = NULL, 
              nCountRNAceiling = NULL,
              pct_mitofloor = NULL, 
              pct_mitoceiling = 50,
              pct_ribofloor = NULL, 
              pct_riboceiling = NULL,
              ambientRNA_thres = 0.5)
)