# remove.packages("monocle3")
devtools::install_github("cysouw/qlcMatrix", upgrade = FALSE)
install.packages("DDRTree")
install.packages("densityClust")
BiocManager::install("monocle.objSingleCell", update = FALSE)
install.packages("fastICA")
BiocManager::install("biocViews", update = FALSE)
# remove.packages("BiocGenerics")
# install.packages("/media/hieunguyen/HNSD01/src/migratory_ccr7_data_analysis/biocgenerics_release_3_9", type = "source", repos = NULL)
BiocManager::install("HSMMSingleCell", update = FALSE)
# install.packages("/media/hieunguyen/HNHD01/offline_pkgs/monocle_2.32.0.tar.gz", type = "source", repos = NULL)
install.packages("/media/hieunguyen/HNHD01/offline_pkgs/monocle_2.30.0/monocle", type = "source", repos = NULL)
# install.packages("/media/hieunguyen/HNHD01/offline_pkgs/monocle_2.32.0", type = "source", repos = NULL)
# install.packages("/media/hieunguyen/HNSD01/src/migratory_ccr7_data_analysis/monocle_2.12.0", type = "source", repos = NULL)
# install.packages("/media/hieunguyen/HNSD01/src/migratory_ccr7_data_analysis/monocle-release/monocle-release-master", type = "source", repos = NULL)
BiocManager::install("tradeSeq", update = FALSE)
# install.packages("/media/hieunguyen/HNSD01/src/migratory_ccr7_data_analysis/tradeseq_release_3_10", type = "source", repos = NULL)n
